
language: objective-c
osx_image: xcode10.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8


before_install:
    - env
    - locale
    - gem install cocoapods --pre --no-document --quiet
    - gem install xcpretty --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Check if the library described by the podspec can be built
    - pod lib lint --allow-warnings
    
    - echo Build
    - xcodebuild clean build -workspace Example/Cleaner.xcworkspace -scheme Cleaner-Example -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c

    - echo Run the tests
    - xcodebuild test -workspace Example/Cleaner.xcworkspace -scheme Cleaner-Example -configuration Debug -destination 'name=iPhone 6s' | xcpretty -c
